### ISSUE TITLE
tools/facts no longer works

### ISSUE THREAD

**Issue by allieoop** [living-room/lovelace#42]
### Description
`tools/facts/` no longer shows existing facts or allows you to create new facts.

### Steps to reproduce
1. npm start
2. go to http://localhost:5000/tools/facts/ (you may need to refresh the page)

You should see a blank screen with an empty fact textbox that doesn't allow you to record facts.

### Console output
```
/Users/allie/workspace/lovelace/node_modules/@living-room/service-js/src/services/dbstream.js:14
        room.off('assert', assertCb)
             ^

TypeError: room.off is not a function
    at DBStream.destroy [as _destroy] (/Users/allie/workspace/lovelace/node_modules/@living-room/service-js/src/services/dbstream.js:14:14)
    at DBStream.destroy (internal/streams/destroy.js:32:8)
    at destroy (/Users/allie/workspace/lovelace/node_modules/destroy/index.js:41:12)
    at listener (/Users/allie/workspace/lovelace/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/allie/workspace/lovelace/node_modules/on-finished/index.js:100:5)
    at callback (/Users/allie/workspace/lovelace/node_modules/ee-first/index.js:55:10)
    at Socket.onevent (/Users/allie/workspace/lovelace/node_modules/ee-first/index.js:93:5)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:548:12)
```

**Comment by jedahan** [comment]
I'm not sure what exact commit fixed this, but it should be working on latest version. git pull, npm install, npm start should do the trick, let me know if its still failing.

**Comment by allieoop** [comment]
I'm still seeing `TypeError: room.off is not a function` when I refresh the facts page.

**Comment by jedahan** [comment]
Hmm can you try `rm -r node_modules; git pull; npm install` ? Maybe npm is acting wonky...

**Comment by allieoop** [comment]
idk, that's what I did:

```
~/workspace/lovelace(master○) » rm -rf node_modules
npm install%                                                                    ~/workspace/lovelace(master○) » npm install
[fsevents] Success: "/Users/allie/workspace/lovelace/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
added 1139 packages from 577 contributors in 24.853s
~/workspace/lovelace(master⚡) » npm start
┌───────────────────────────┐
│                           │
│   displays and tools at   │
│   http://localhost:5000   │
│                           │
└───────────────────────────┘
╭──────────────────────────────╮
│                              │
│   processes                  │
│     green is active          │
│     * has step fn            │
│                              │
│     animalIlluminator        │
│     animalMaker              │
│     boundingBoxIlluminator   │
│     clock                    │
│     debugIlluminator         │
│     fear                     │
│     fearIlluminator          │
│     hueIlluminator           │
│     keyboardIlluminator      │
│     keyboardTerminal         │
│     mcuManager               │
│     mouse                    │
│     move                     │
│     networkIlluminator       │
│     sight                    │
│     sightIlluminator         │
│     sightlines               │
│                              │
╰──────────────────────────────╯
/Users/allie/workspace/lovelace/node_modules/@living-room/service-js/src/services/dbstream.js:14
        room.off('assert', assertCb)
             ^

TypeError: room.off is not a function
    at DBStream.destroy [as _destroy] (/Users/allie/workspace/lovelace/node_modules/@living-room/service-js/src/services/dbstream.js:14:14)
    at DBStream.destroy (internal/streams/destroy.js:32:8)
    at destroy (/Users/allie/workspace/lovelace/node_modules/destroy/index.js:41:12)
    at listener (/Users/allie/workspace/lovelace/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/allie/workspace/lovelace/node_modules/on-finished/index.js:100:5)
    at callback (/Users/allie/workspace/lovelace/node_modules/ee-first/index.js:55:10)
    at Socket.onevent (/Users/allie/workspace/lovelace/node_modules/ee-first/index.js:93:5)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:548:12)
```

**Comment by allieoop** [comment]
I just tried again to make sure: 
```
~/workspace/lovelace(master⚡) » rm -r node_modules
~/workspace/lovelace(master⚡) » git pull
Already up-to-date.
~/workspace/lovelace(master⚡) » npm install
[fsevents] Success: "/Users/allie/workspace/lovelace/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
added 1139 packages from 577 contributors in 31.063s
~/workspace/lovelace(master⚡) » npm start
┌───────────────────────────┐
│                           │
│   displays and tools at   │
│   http://localhost:5000   │
│                           │
└───────────────────────────┘
╭──────────────────────────────╮
│                              │
│   processes                  │
│     green is active          │
│     * has step fn            │
│                              │
│     animalIlluminator        │
│     animalMaker              │
│     boundingBoxIlluminator   │
│     clock                    │
│     debugIlluminator         │
│     fear                     │
│     fearIlluminator          │
│     hueIlluminator           │
│     keyboardIlluminator      │
│     keyboardTerminal         │
│     mcuManager               │
│     mouse                    │
│     move                     │
│     networkIlluminator       │
│     sight                    │
│     sightIlluminator         │
│     sightlines               │
│                              │
╰──────────────────────────────╯
/Users/allie/workspace/lovelace/node_modules/@living-room/service-js/src/services/dbstream.js:14
        room.off('assert', assertCb)
             ^

TypeError: room.off is not a function
    at DBStream.destroy [as _destroy] (/Users/allie/workspace/lovelace/node_modules/@living-room/service-js/src/services/dbstream.js:14:14)
    at DBStream.destroy (internal/streams/destroy.js:32:8)
    at destroy (/Users/allie/workspace/lovelace/node_modules/destroy/index.js:41:12)
    at listener (/Users/allie/workspace/lovelace/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/allie/workspace/lovelace/node_modules/on-finished/index.js:100:5)
    at callback (/Users/allie/workspace/lovelace/node_modules/ee-first/index.js:55:10)
    at Socket.onevent (/Users/allie/workspace/lovelace/node_modules/ee-first/index.js:93:5)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:548:12)


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.7.1 → 6.1.0    │
   │       Run npm i npm to update       │
   │                                     │
   ╰─────────────────────────────────────╯
```

**Comment by jedahan** [comment]
That is super frustrating im gonna try a fresh clone...

**Comment by jedahan** [comment]
What version of node? Im on node v10.3.0, macOS 10.13.4, tested in chromium and firefox.

**Comment by allieoop** [comment]
Looks like it works with node v10.3.0! Here's what I tested (all on chrome 67, macOS 10.13.4):

### Works
* v10.3.0 (npm v6.1.0)

### Doesn't work
* v8.11.2 (npm v5.6.0)
  ```
  (See error mentioned above)
  ```

* v6.14.2 (npm v3.10.10)
  ```node
  node_modules/@living-room/service-js/service.js:17
    async listen ({ verbose } = { verbose: true }) {
          ^^^^^^
  
  SyntaxError: Unexpected identifier
  ```

**Comment by jedahan** [comment]
Maybe we could add https://github.com/typicode/please-upgrade-node as `npm run check` and make sure we call that script before npm start, npm install, etc...

**Comment by jedahan** [comment]
Okay now if you run `npm start` here or in service-js it will bail and ask you to upgrade nicely
